[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.3.2"

[context.deploy-preview]
  command = "yarn build-preview"
  
[[redirects]]
  from = "https://angry-wilson-7cb707.netlify.com/*"
  to = "https://casteasoft.com/:splat"
  status = 301
  force = false

[[redirects]]
  from = "http://angry-wilson-7cb707.netlify.com/*"
  to = "https://casteasoft.com/:splat"
  status = 301
  force = false

[[redirects]]
  from = "http://casteasoft.com/*"
  to = "https://casteasoft.com/:splat"
  status = 301
  force = false
